import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav";
import { navData } from "@/data/nav-data";
import Footer from "@/components/nav/Footer";

const poppins = Poppins({ weight: ["100", "300", "500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Poke-test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} pt-12`}>
        <Navbar links={navData} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
